# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[line_break]
disabled = true

[hostname]
format = '[$ssh_symbol](bold blue)'
disabled = false
